name: SpigotBuilder
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'azul'

      - name: Build Spigot
        run: java -jar BuildTools.jar --rev 1.20.4
      
      - uses: actions/upload-artifact@v3
        with:
          name: SpigotBuild
          path: ./*
